comp_service/urls.py
from django.urls import path, include
from .views import *

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
    path('services/', include([
        path('', ServiceListView.as_view(), name='services'),
        path('<slug:slug>/', ServiceDetailView.as_view(), name='service_detail'),
    ])),
    path('photo/', PhotosList.as_view(), name='photo'),
    path('about/', about, name='about'),
    path('contact/', contact_view, name='contact'),
    path('user/', include([
        path('login/', LoginUser.as_view(), name='login'),
        path('logout/', logout_user, name='logout'),
        path('<str:username>', profile, name='profile'),
        path('<str:username>/<int:order_id>/', order_detail, name='order_detail'),
    ])),
]

kurs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('comp_service.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comp_service/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
from django.utils.text import slugify


def upload_to(instance, filename):
    return f'checks/{instance.user.username}/{filename}'


class Photo(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(verbose_name='Фото',
                              upload_to='gallery/%Y/%m/%d/',
                              null=False,
                              blank=False
                              )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='photos',
                               )
    published = models.DateTimeField(default=timezone.now, db_index=True)

    class Meta:
        verbose_name_plural = 'Фото'
        verbose_name = 'Фото'
        ordering = ('-published',)


class Service(models.Model):                                                # Услуга
    title = models.CharField(max_length=100)                                # Название услуги
    description = models.TextField()                                        # Описание
    cost = models.IntegerField(null=False, blank=False)                     # Стоимость
    published = models.DateTimeField(default=timezone.now, db_index=True)   # Дата добавления
    slug = models.SlugField(max_length=250)                                 # Ссылка услуги

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:service', kwargs={'slug': self.slug})

    class Meta:
        verbose_name_plural = 'Услуги'
        verbose_name = 'Услуга'
        ordering = ('-published',)


class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ('created', 'Создан'),
        ('in_progress', 'В работе'),
        ('ready', 'Готов'),
        ('completed', 'Выполнен'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)                                    # Пользователь, который оставил заказ
    services = models.ManyToManyField(Service)                                                  # Услуги, входящие в заказ
    order_date = models.DateTimeField(auto_now_add=True)                                        # Дата заказа
    status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='created')   # Статус заказа
    check_file = models.FileField(upload_to=upload_to, null=True, blank=True)                   # Поле для чека
    slug = models.SlugField(max_length=250, unique=True)

    def get_absolute_url(self):
        return reverse('main:order', kwargs={'slug': self.slug})

    def total_cost(self):
        return sum(service.cost for service in self.services.all())

    def __str__(self):
        return f"Order #{self.pk} by {self.user.username} on {self.order_date}"

    class Meta:
        verbose_name_plural = 'Заказы'
        verbose_name = 'Заказ'
        ordering = ('-order_date',)

comp_service/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control required'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control required'}))


class ContactForm(forms.Form):
    email = forms.EmailField(label='Email', required=True, widget=forms.EmailInput(attrs={'class': 'form-group'}))
    name = forms.CharField(label='Имя', required=True)
    mess = forms.CharField(label='Сообщение', widget=forms.Textarea, required=True)

comp_service/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from itertools import chain
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import HttpResponse
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test

from .models import *
from .forms import ContactForm, LoginUserForm


# Create your views here.


class PhotosList(ListView):
    model = Photo
    template_name = 'comp_service/photos.html'
    paginate_by = 5
    context_object_name = 'photos'

    def get_queryset(self):
        return Photo.objects.all().order_by('-published')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = Paginator(self.get_queryset(), self.paginate_by)
        page = self.request.GET.get('page')

        try:
            photos = paginator.page(page)
        except PageNotAnInteger:
            # Если страница не является целым числом, поставим первую страницу
            photos = paginator.page(1)
        except EmptyPage:
            # Если страница находится за пределами доступного диапазона, поставим последнюю страницу
            photos = paginator.page(paginator.num_pages)

        context['object_list'] = photos
        return context


def main(request):
    return render(request, 'comp_service/main.html')


def about(request):
    if request.method == 'GET':
        form = ContactForm()
    elif request.method == 'POST':
        # если метод POST, проверим форму и отправим письмо
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['mess']
            recepients = [settings.EMAIL_HOST_USER]
            send_mail(name + ' -- ' + email, message, settings.EMAIL_HOST_USER, recepients)
            return redirect('main:about')
    return render(request, 'comp_service/about.html', {'form': form})


class ServiceListView(ListView):
    model = Service
    template_name = 'comp_service/services.html'
    context_object_name = 'services'


class ServiceDetailView(DetailView):
    model = Service
    template_name = 'comp_service/service_detail.html'
    context_object_name = 'service'


def contact_view(request):
    # если метод GET, вернем форму
    if request.method == 'GET':
        form = ContactForm()
    elif request.method == 'POST':
        # если метод POST, проверим форму и отправим письмо
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['mess']
            recepients = [settings.EMAIL_HOST_USER]
            send_mail(name + ' -- ' + email, message, settings.EMAIL_HOST_USER, recepients)
            return redirect('main:main')
    else:
        return HttpResponse('Неверный запрос.')
    return render(request, 'comp_service/contact.html', {'form': form})


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'comp_service/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return dict(list(context.items()))

    def get_success_url(self):
        return reverse_lazy('main:main')


@login_required
def logout_user(request):
    logout(request)
    return redirect('main:main')


@login_required
def order_detail(request, username, order_id):
    order = get_object_or_404(Order, id=order_id)
    # Проверяем доступ к заказу
    if not can_view_order(request.user, order):
        # Обработка случая, когда доступ запрещен
        return redirect('main:main')
    return render(request, 'comp_service/order_detail.html', {'order': order,
                                                              'username': username})


@login_required
def profile(request, username):
    profile_user = User.objects.get(username=username)
    context = {'user': profile_user,
               'orders': Order.objects.filter(user=request.user)}
    if not can_view_profile(request.user, profile_user):
        # Обработка случая, когда доступ запрещен
        return redirect('main:main')
    return render(request, 'comp_service/profile.html', context)


def can_view_order(user, order):
    return user.is_authenticated and (user == order.user or user.is_staff)


def can_view_profile(user, profile_user):
    return user.is_authenticated and (user == profile_user or user.is_staff)

templates/comp_service/about.html
{% extends "comp_service/layout/base.html" %}
{% load static %}
{% block title %}УлКомп | О нас{% endblock %}
{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">О нас</h1>

        <p>
            Добро пожаловать в компьютерную мастерскую! Мы - команда профессиональных специалистов, готовых помочь вам
            с решением любых проблем, связанных с вашими компьютерами.
        </p>

        <p>
            Наша мастерская предоставляет широкий спектр услуг, включая ремонт и обслуживание компьютеров, настройку
            программного обеспечения, восстановление данных, а также консультации по выбору и апгрейду оборудования.
        </p>

        <p>
            Мы стремимся предоставлять высококачественные услуги и создавать удобную среду для наших клиентов. Наша цель -
            сделать ваш опыт использования компьютеров максимально комфортным и эффективным.
        </p>

        <p>
            Свяжитесь с нами, если у вас есть вопросы или если вам требуется помощь. Мы готовы помочь вам в любое время!
        </p>
    </div>
    <div class="container mt-5">
        <h4>Форма обратной связи:</h4>
        <form method="post" class="form-contact form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </div>
{% endblock %}

templates/comp_service/contact.html
{% extends "comp_service/layout/base.html" %}
{% load static %}
{% block title %}УлКомп | Контакты{% endblock %}
{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Контакты</h1>

        <div class="row">
            <div class="col-md-6">
                <h4>Адрес:</h4>
                <div class="adress"><i class="fa fa-map-marker" aria-hidden="true"></i> г. Ульяновск пр-т Ульяновский, д 13, 432072</div>

                <h4>Электронная почта:</h4>
                <a href="mailto:sevabasharin@mail.ru" class="email"><i class="fa fa-envelope" aria-hidden="true"></i>sevabasharin@mail.ru</a>

                <h4>Телефон:</h4>
                <a href="tel:+79121231212" class="phone"> <i class="fa fa-phone" aria-hidden="true"></i>+7 (912) 123-12-12</a>

                <h4>Интерактивная карта:</h4>
                <div style="position:relative;overflow:hidden;">
                    <a href="https://yandex.ru/maps/195/ulyanovsk/?utm_medium=mapframe&utm_source=maps"
                       style="color:#eee;font-size:12px;position:absolute;top:0px;">Ульяновск</a>
                    <a href="https://yandex.ru/maps/195/ulyanovsk/house/ulyanovskiy_prospekt_13/YEEYcwBnSEADQFtufX92d31iZQ==/?indoorLevel=1&ll=48.578102%2C54.375834&utm_medium=mapframe&utm_source=maps&z=18.8"
                       style="color:#eee;font-size:12px;position:absolute;top:14px;">Ульяновский проспект, 13 — Яндекс Карты</a>
                    <iframe src="https://yandex.ru/map-widget/v1/?indoorLevel=1&ll=48.578102%2C54.375834&mode=whatshere&whatshere%5Bpoint%5D=48.577039%2C54.376798&whatshere%5Bzoom%5D=17&z=18.8" width="500" height="400" frameborder="1" allowfullscreen="true" style="position:relative;"></iframe>
                </div>
            </div>

            <div class="col-md-6">
                <h4>Форма обратной связи:</h4>
                <form method="post" class="form-contact form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/comp_service/login.html
{% extends "comp_service/layout/base.html" %}
{% load static %}
{% block title %}УлКомп | Авторизация{% endblock %}
{% block content %}
    <div class="authorization">
    <div class="container" id="regist">
        <div class="push50"></div>
        <div class="auto-wrapper">
            <div class="rf">
                <form method="post" name="login">
                    <h2>Авторизация</h2>
                    <div class="push30"></div>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div>
                        <input type="submit" class="button btn" value="Войти" />
                    </div>
                </form>
            </div>
        </div>

        <div class="push50"></div>
    </div>
</div>
{% endblock %}

templates/comp_service/main.html
{% extends "comp_service/layout/base.html" %}
{% load static %}
{% block title %}УлКомп | Главная{% endblock %}
{% block content %}
    <div class="container mt-4">
        <div class="jumbotron">
            <h1 class="display-4">Добро пожаловать в наш компьютерный сервис</h1>
            <p class="lead">Мы здесь, чтобы вам помочь с вашими компьютерными потребностями.</p>
            <hr class="my-4">
            <p>Мы предоставляем качественные услуги по обслуживанию и ремонту компьютеров.</p>
            <a class="btn btn-primary btn-lg" href="{% url 'main:about' %}" role="button">Узнать больше</a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card mb-4 d-flex flex-column h-100">
                <img src="{% static 'comp_service/img/install_win.jpg' %}" class="card-img-top" alt="Услуга 1">
                <div class="card-body flex-fill">
                    <h5 class="card-title">Установка Windows</h5>
                    <p class="card-text">Профессиональная установка, настройка и активация операционной системы Windows.</p>
                    <a href="{% url 'main:service_detail' slug='ustanovka-windows' %}" class="btn btn-primary mt-auto">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="card mb-4 d-flex flex-column h-100">
                <img src="{% static 'comp_service/img/XXL.jpg' %}" class="card-img-top" alt="Услуга 2">
                <div class="card-body flex-fill">
                    <h5 class="card-title">Ремонт ПК</h5>
                    <p class="card-text">Комплексный ремонт и обслуживание компьютеров. Быстрая диагностика и устранение аппаратных и программных сбоев для восстановления полной функциональности ПК.</p>
                    <a href="{% url 'main:service_detail' slug='remont-pk' %}" class="btn btn-primary mt-auto">Подробнее</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/comp_service/order_detail.html
{% extends "comp_service/layout/base.html" %}
{% load static %}
{% block title %}УлКомп | Детали заказа{% endblock %}
{% block content %}
    <div class="container mt-5">
    <h1 class="mb-4">Детали заказа #{{ order.pk }}</h1>

    <div class="card mb-3">
        <div class="card-header">
            Заказ #{{ order.pk }}
        </div>
        <div class="card-body">
            <h5 class="card-title">Дата заказа: {{ order.order_date }}</h5>
            <p class="card-text">
                Услуги в заказе:
                <ul>
                    {% for service in order.services.all %}
                        <li>{{ service.title }} - {{ service.cost }} рублей</li>
                    {% endfor %}
                </ul>
            </p>
            <p class="card-text">Статус заказа: {{ order.get_status_display }}</p>
            <p class="card-text">Сумма заказа: {{ order.total_cost }} рублей</p>
            {% if order.check_file %}
                <p class="card-text">
                    <a href="{{ order.check_file.url }}" target="_blank">Скачать чек</a>
                </p>
            {% endif %}
        </div>
    </div>

    <a href="{% url 'main:profile' username=username %}" class="btn btn-secondary">Назад к заказам</a>
</div>
{% endblock %}

templates/comp_service/photos.html
{% extends "comp_service/layout/base.html" %}
{% load static %}
{% block title %}УлКомп | Фото{% endblock %}
{% block content %}
    <div class="container mt-5">
            <h1 class="mb-4">Галерея</h1>

            <div class="row">
                {% for photo in object_list %}
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            <img src="{{ photo.image.url }}" class="card-img-top" alt="{{ photo.title }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ photo.title }}</h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <div class="pagination justify-content-center">
                <span class="step-links">
                    {% if object_list.has_previous %}
                        <a href="?page=1">&laquo; первая</a>
                        <a href="?page={{ object_list.previous_page_number }}">предыдущая</a>
                    {% endif %}

                    <span class="current">
                        Страница {{ object_list.number }} из {{ object_list.paginator.num_pages }}.
                    </span>

                    {% if object_list.has_next %}
                        <a href="?page={{ object_list.next_page_number }}">следующая</a>
                        <a href="?page={{ object_list.paginator.num_pages }}">последняя &raquo;</a>
                    {% endif %}
                </span>
            </div>
    </div>
{% endblock %}

templates/comp_service/profile.html
{% extends "comp_service/layout/base.html" %}
{% load static %}
{% block title %}УлКомп | Профиль{% endblock %}
{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Ваши заказы</h1>

        {% for order in orders %}
            <div class="card mb-3">
                <div class="card-header">
                    <a class="advance-link" href="{% url 'main:order_detail' username=user.username order_id=order.pk %}">Заказ #{{ order.pk }}</a>
                </div>
                <div class="card-body">
                    <h5 class="card-title">Дата заказа: {{ order.order_date }}</h5>
                    <p class="card-text">
                        Услуги в заказе:
                        <ul>
                            {% for service in order.services.all %}
                                <li>{{ service.title }} - {{ service.cost }} рублей</li>
                            {% endfor %}
                        </ul>
                    </p>
                    <p class="card-text">Сумма заказа: {{ order.total_cost }} рублей</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/comp_service/service_detail.html
{% extends "comp_service/layout/base.html" %}
{% load static %}
{% block title %}УлКомп | {{ service.title }}{% endblock %}
{% block content %}
    <h1>{{ service.title }}</h1>
    <p>{{ service.description }}</p>
    <p>Стоимость: {{ service.cost }} рублей</p>
{% endblock %}

templates/comp_service/services.html
{% extends "comp_service/layout/base.html" %}
{% load static %}
{% block title %}УлКомп | Услуги{% endblock %}
{% block content %}
    <div class="container mt-5">
        <h1 class="mb-4">Услуги</h1>

        <ul class="list-group">
            {% for service in services %}
                <li class="list-group-item">
                    <a href="{% url 'main:service_detail' slug=service.slug %}">
                        <h4>{{ service.title }}</h4>
                        <p>{{ service.description }}</p>
                        <p>Стоимость: {{ service.cost }} рублей</p>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}