comp_service/urls.py
from django.urls import path, include
from .views import *

app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
    path('services/', include([
        path('', ServiceListView.as_view(), name='services'),
        path('<slug:slug>/', ServiceDetailView.as_view(), name='service_detail'),
    ])),
    path('photo/', PhotosList.as_view(), name='photo'),
    path('about/', about, name='about'),
    path('contact/', contact_view, name='contact'),
    path('user/', include([
        path('login/', LoginUser.as_view(), name='login'),
        path('logout/', logout_user, name='logout'),
        path('<str:username>', profile, name='profile'),
        path('<str:username>/<int:order_id>/', order_detail, name='order_detail'),
    ])),
]

kurs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('comp_service.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comp_service/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
from django.utils.text import slugify


def upload_to(instance, filename):
    return f'checks/{instance.user.username}/{filename}'


class Photo(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(verbose_name='Фото',
                              upload_to='gallery/%Y/%m/%d/',
                              null=False,
                              blank=False
                              )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='photos',
                               )
    published = models.DateTimeField(default=timezone.now, db_index=True)

    class Meta:
        verbose_name_plural = 'Фото'
        verbose_name = 'Фото'
        ordering = ('-published',)


class Service(models.Model):                                                # Услуга
    title = models.CharField(max_length=100)                                # Название услуги
    description = models.TextField()                                        # Описание
    cost = models.IntegerField(null=False, blank=False)                     # Стоимость
    published = models.DateTimeField(default=timezone.now, db_index=True)   # Дата добавления
    slug = models.SlugField(max_length=250)                                 # Ссылка услуги

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:service', kwargs={'slug': self.slug})

    class Meta:
        verbose_name_plural = 'Услуги'
        verbose_name = 'Услуга'
        ordering = ('-published',)


class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ('created', 'Создан'),
        ('in_progress', 'В работе'),
        ('ready', 'Готов'),
        ('completed', 'Выполнен'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)                                    # Пользователь, который оставил заказ
    services = models.ManyToManyField(Service)                                                  # Услуги, входящие в заказ
    order_date = models.DateTimeField(auto_now_add=True)                                        # Дата заказа
    status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='created')   # Статус заказа
    check_file = models.FileField(upload_to=upload_to, null=True, blank=True)                   # Поле для чека
    slug = models.SlugField(max_length=250, unique=True)

    def get_absolute_url(self):
        return reverse('main:order', kwargs={'slug': self.slug})

    def total_cost(self):
        return sum(service.cost for service in self.services.all())

    def __str__(self):
        return f"Order #{self.pk} by {self.user.username} on {self.order_date}"

    class Meta:
        verbose_name_plural = 'Заказы'
        verbose_name = 'Заказ'
        ordering = ('-order_date',)

comp_service/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-control required'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-control required'}))


class ContactForm(forms.Form):
    email = forms.EmailField(label='Email', required=True, widget=forms.EmailInput(attrs={'class': 'form-group'}))
    name = forms.CharField(label='Имя', required=True)
    mess = forms.CharField(label='Сообщение', widget=forms.Textarea, required=True)

comp_service/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from itertools import chain
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.http import HttpResponse
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import user_passes_test

from .models import *
from .forms import ContactForm, LoginUserForm


# Create your views here.


class PhotosList(ListView):
    model = Photo
    template_name = 'comp_service/photos.html'
    paginate_by = 5
    context_object_name = 'photos'

    def get_queryset(self):
        return Photo.objects.all().order_by('-published')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = Paginator(self.get_queryset(), self.paginate_by)
        page = self.request.GET.get('page')

        try:
            photos = paginator.page(page)
        except PageNotAnInteger:
            # Если страница не является целым числом, поставим первую страницу
            photos = paginator.page(1)
        except EmptyPage:
            # Если страница находится за пределами доступного диапазона, поставим последнюю страницу
            photos = paginator.page(paginator.num_pages)

        context['object_list'] = photos
        return context


def main(request):
    return render(request, 'comp_service/main.html')


def about(request):
    if request.method == 'GET':
        form = ContactForm()
    elif request.method == 'POST':
        # если метод POST, проверим форму и отправим письмо
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['mess']
            recepients = [settings.EMAIL_HOST_USER]
            send_mail(name + ' -- ' + email, message, settings.EMAIL_HOST_USER, recepients)
            return redirect('main:about')
    return render(request, 'comp_service/about.html', {'form': form})


class ServiceListView(ListView):
    model = Service
    template_name = 'comp_service/services.html'
    context_object_name = 'services'


class ServiceDetailView(DetailView):
    model = Service
    template_name = 'comp_service/service_detail.html'
    context_object_name = 'service'


def contact_view(request):
    # если метод GET, вернем форму
    if request.method == 'GET':
        form = ContactForm()
    elif request.method == 'POST':
        # если метод POST, проверим форму и отправим письмо
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['mess']
            recepients = [settings.EMAIL_HOST_USER]
            send_mail(name + ' -- ' + email, message, settings.EMAIL_HOST_USER, recepients)
            return redirect('main:main')
    else:
        return HttpResponse('Неверный запрос.')
    return render(request, 'comp_service/contact.html', {'form': form})


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'comp_service/login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return dict(list(context.items()))

    def get_success_url(self):
        return reverse_lazy('main:main')


@login_required
def logout_user(request):
    logout(request)
    return redirect('main:main')


@login_required
def order_detail(request, username, order_id):
    order = get_object_or_404(Order, id=order_id)
    # Проверяем доступ к заказу
    if not can_view_order(request.user, order):
        # Обработка случая, когда доступ запрещен
        return redirect('main:main')
    return render(request, 'comp_service/order_detail.html', {'order': order,
                                                              'username': username})


@login_required
def profile(request, username):
    profile_user = User.objects.get(username=username)
    context = {'user': profile_user,
               'orders': Order.objects.filter(user=request.user)}
    if not can_view_profile(request.user, profile_user):
        # Обработка случая, когда доступ запрещен
        return redirect('main:main')
    return render(request, 'comp_service/profile.html', context)


def can_view_order(user, order):
    return user.is_authenticated and (user == order.user or user.is_staff)


def can_view_profile(user, profile_user):
    return user.is_authenticated and (user == profile_user or user.is_staff)

templates/comp_service/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
        <title>{{title}}</title>
    </head>
        <body>
            <header>
                    <nav class="navbar navbar-light bg-light display:flex justify-content:space-between">
                        <div class="d-flex">
                            <a class="navbar-brand" href="{% url 'main:main' %}">УлКомп</a>
                            <a class="navbar-brand" href="{% url 'main:services' %}">Услуги</a>
                            <a class="navbar-brand" href="{% url 'main:about' %}">О нас</a>
                            <a class="navbar-brand" href="{% url 'main:contact' %}">Контакты</a>
                            <a class="navbar-brand" href="{% url 'main:photo' %}">Галерея</a>
                        </div>
                        {% if user.is_authenticated %}
                            <div class="d-flex">
                                <ul class="navbar-nav mr-auto">
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle relative" id="navbarDropdown" role="button"
                                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                                           style="position: relative">
                                            {{ user.username }}
                                        </a>
                                        <div class="dropdown-menu" style="position: absolute;right:0;left:auto !important" aria-labelledby="navbarDropdown">
                                            {% if user.is_staff %}
                                                <a class="dropdown-item" href="{% url 'admin:index' %}">Админка</a>
                                            {% endif %}
                                            <a class="dropdown-item" href="{% url 'main:profile' user.username %}">Профиль</a>
                                            <div class="dropdown-divider"></div>
                                            <a class="dropdown-item" href="{% url 'main:logout' %}">Выход</a>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        {% else %}
                            <a class="navbar-brand" href="{% url 'main:login' %}">Вход</a>
                        {% endif %}
                    </nav>
            </header>
            {% if messages %}
                <div class="messages">
                {% for message in messages %}
                    <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </div>
                {% endfor %}
                </div>
            {% endif %}
            <!-- Begin page content -->
            <main role="main" class="container">
                {% block content %}{% endblock %}
            </main>
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        </body>
</html>